# Generated by Django 4.2.10 on 2025-07-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="background_color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="icon",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
