# Generated by Django 4.2.10 on 2025-08-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobilepaymentwallet",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
