# Generated by Django 4.2.10 on 2025-07-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_collection_background_color_collection_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="image",
        ),
        migrations.AddField(
            model_name="productimage",
            name="image_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
