# Generated by Django 4.2.10 on 2025-08-20 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_rename_active_product_is_active_favoriteproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="shop.mobilepaymentwallet",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="shop.address",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("S", "Shipped"),
                    ("O", "Out for Delivery"),
                    ("D", "Delivered"),
                    ("C", "Completed"),
                    ("F", "Failed"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
