# Generated by Django 4.2.8 on 2023-12-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_customer_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
