# Generated by Django 4.2.10 on 2024-02-14 15:01

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='shop/images', validators=[shop.validators.validate_file_size]),
        ),
    ]
