name: notify-developer
run-name: ${{ github.actor }} pushed to ${{ github.repository }}
on: 
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: NEW PUSH TO ${{ github.repository }} REPOSITORY 
        body: |
          A new push has been made to the ${{ github.repository }} repository by ${{ github.actor }}.
          Commit message: ${{ github.event.head_commit.message }}
        to: ${{ secrets.MAIL_USERNAME }}
        from: ${{ secrets.MAIL_USERNAME }}
